import { Router, type IRouter } from "express";
import healthRouter from "./health";
import agentsRouter from "./agents";
import channelsRouter from "./channels";
import tasksRouter from "./tasks";
import telemetryRouter from "./telemetry";
import swarmRouter from "./swarm";
import commandsRouter from "./commands";
import steelRouter from "./steel";
import aiRouter from "./ai";
import neurobuddyRouter from "./neurobuddy";
import externalRouter from "./external";
import integrationsRouter from "./integrations";
import selfCheckRouter from "./selfCheck";
import authRouter from "./auth";
import vaultRouter from "./vault";
import socialRouter from "./social";
import uploadsRouter from "./uploads";
import worldRouter from "./world";
import { requireOperator } from "../lib/auth";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/agents", agentsRouter);
router.use("/channels", channelsRouter);
router.use("/tasks", tasksRouter);
router.use(telemetryRouter);
router.use("/swarm", swarmRouter);
router.use(commandsRouter);
router.use(steelRouter);
router.use(aiRouter);
router.use(uploadsRouter);
router.use(worldRouter);
router.use(neurobuddyRouter);
router.use(externalRouter);
router.use(integrationsRouter);
router.use(selfCheckRouter);
router.use(authRouter);
router.use(requireOperator, vaultRouter);
router.use(requireOperator, socialRouter);

export default router;
